### ISSUE TITLE
Archive Error: ApigeeUIEventSegmentSelected.o was built without full bitcode

### ISSUE THREAD

**Issue by huntermonk** [apigee/apigee-ios-sdk#128]
When attempting to archive an Xcode project with the `2.0.20` version of the SDK, I get the following error:

> bitcode bundle could not be generated because `'../ApigeeiOSSDK.framework/ApigeeiOSSDK(ApigeeUIEventSegmentSelected.o)'` was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64

I've attempted several fixes such as adding `-fembed-bitcode` to "Other C Flags" as [described here.](http://stackoverflow.com/questions/31233395/ios-library-to-bitcode)

Of course, I can successfully archive by turning bitcode off, but that's not preferable. Let me know what I can do to help fix this!

**Comment by RobertWalsh** [comment]
So I am pretty sure I figured out the issue here.  When we build the framework we use the `xcodebuild` command. Adding the `-fembed-bitcode` to the command seems to create the framework with the bitcode configured correctly.  

See https://github.com/apigee/apigee-ios-sdk/pull/129.  It would be appreciated if you could try out that PR and let me know if how it works on your end.

**Comment by huntermonk** [comment]
Excellent. That was indeed the problem 👍🏼.

I was able to build and archive with bitcode enabled. Thanks, I appreciate the fix.

**Comment by RobertWalsh** [comment]
Great will merge and create a new version.  Thanks!

**Comment by RobertWalsh** [comment]
[v2.0.21](https://github.com/apigee/apigee-ios-sdk/releases/tag/v2.0.21) is now available.
